In [1]:
import numpy as np
from optimization import *

+ What would happen if the total allocated resource increases?
+ What would happen if the initial accuracy of one robot would be higher?
+ What would happen if the initial accuracies are the same but higher compared to this case for a fixed total allocated resource? (I think this will result in the same conclusion obtained from the first item.)
+ What would happen if the initial hardness of one robot would be higher?
+ What would happen if the hardness of the robots are the same and higher?

In [2]:
table_case_hand = {'T': 0.7, 'E_init': np.array([[0.007],[0.007]]), 'gamma_vec': np.array([[0.25],[0.25]])}
table_case_moreResource  = {'T': 1.0, 'E_init': np.array([[0.007],[0.007]]), 'gamma_vec': np.array([[0.25],[0.25]])}
table_case_oneAccHigher = {'T': 0.7, 'E_init': np.array([[0.8],[0.007]]), 'gamma_vec': np.array([[0.25],[0.25]])}
table_case_bothAccHigher = {'T': 0.7, 'E_init': np.array([[0.3],[0.3]]), 'gamma_vec': np.array([[0.25],[0.25]])}
table_case_oneHardHigher  = {'T': 0.7, 'E_init': np.array([[0.007],[0.007]]), 'gamma_vec': np.array([[0.5],[0.25]])}
table_case_bothHardHigher  = {'T': 0.7, 'E_init': np.array([[0.007],[0.007]]), 'gamma_vec': np.array([[0.5],[0.5]])}
table_case_saturated  = {'T': 2.0, 'E_init': np.array([[0.007],[0.007]]), 'gamma_vec': np.array([[0.25],[0.25]])}

In [3]:
configs  = [table_case_hand, table_case_moreResource, table_case_oneAccHigher, table_case_bothAccHigher, table_case_oneHardHigher, table_case_bothHardHigher, table_case_saturated]
np.random.seed(40)
for con in configs:
    print("Configuration is: ")
    print(con)
    print("FS Allocation: ")
    alloc, _ = fairSynergy1D(con)
    fs = calcAcc1D(alloc+con['E_init'], con['gamma_vec'])
    print("Utilities:")
    print(fs)
    print("Dual Variables: ")
    print(calcDualForBenchmarks(alloc, con))
    print()
    print("Uniform Allocation: ")
    eu, _ = uniformAssignment1D(con)
    print("Allocated Resources: ")
    print(eu)
    print("Utilities:")
    print(calcAcc1D(eu+con['E_init'], con['gamma_vec']))
    print("Dual Variables: ")
    print(calcDualForBenchmarks(eu, con))
    print()
    print("Random Allocation")
    er, _ = randomAssignment1D(con)
    print("Allocated Resources: ")
    print(er)
    print("Utilities:")
    print(calcAcc1D(eu+con['E_init'], con['gamma_vec']))
    print("Dual Variables: ")
    print(calcDualForBenchmarks(er, con))

    print()
    print()

Configuration is: 
{'T': 0.7, 'E_init': array([[0.007],
       [0.007]]), 'gamma_vec': array([[0.25],
       [0.25]])}
FS Allocation: 
Utilities:
[[0.77297786]
 [0.77297786]]
Dual Variables: 
[[0.54130102]
 [0.54130102]]

Uniform Allocation: 
Allocated Resources: 
[[0.35]
 [0.35]]
Utilities:
[[0.77297786]
 [0.77297786]]
Dual Variables: 
[[0.54130102]
 [0.54130102]]

Random Allocation
Allocated Resources: 
[[0.63133811]
 [0.06866189]]
Utilities:
[[0.77297786]
 [0.77297786]]
Dual Variables: 
[[0.35006761]
 [1.73293444]]


Configuration is: 
{'T': 1.0, 'E_init': array([[0.007],
       [0.007]]), 'gamma_vec': array([[0.25],
       [0.25]])}
FS Allocation: 
Utilities:
[[0.84382423]
 [0.84382423]]
Dual Variables: 
[[0.4160869]
 [0.4160869]]

Uniform Allocation: 
Allocated Resources: 
[[0.5]
 [0.5]]
Utilities:
[[0.84382423]
 [0.84382423]]
Dual Variables: 
[[0.4160869]
 [0.4160869]]

Random Allocation
Allocated Resources: 
[[0.82101961]
 [0.17898039]]
Utilities:
[[0.84382423]
 [0.84382423]]
Du